### ISSUE TITLE
wget: server returned error: HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by pasuva** [hydazz/docker-readarr#1]
When I install the docker with the last image, the docker appears unhealthy and I see this error: wget: server returned error: HTTP/1.1 404 Not Found

**Comment by hydazz** [comment]
This can be ignored, for some reason `/api/system/status` which is used for the health check does not exist and errors out. I will investigate further soon.

**Comment by hydazz** [comment]
> wget: server returned error: HTTP/1.1 404 Not Found

fixed in [f11503c](https://github.com/hydazz/docker-readarr/commit/d76a63cab00a2b096b433e9273cad1942b9c11c1), pulling the latest docker image should fix your issue. Let me know if it still errors out!
